name: branch "master"

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.config.dirname }}

    strategy:
      fail-fast: false
      matrix:
        config:
#         - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2019.01/gcc-arm-8.2-2019.01-x86_64-arm-eabi.tar.xz",
#             tarname:  "gcc-arm-8.2-2019.01-x86_64-arm-eabi.tar.xz",
#             dirname:  "gcc-arm-8.2-2019.01-x86_64-arm-eabi",
#             prefix:   "arm-eabi-",
#             raspi:    "2" }
#         - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-eabi.tar.xz",
#             tarname:  "gcc-arm-8.3-2019.03-x86_64-arm-eabi.tar.xz",
#             dirname:  "gcc-arm-8.3-2019.03-x86_64-arm-eabi",
#             prefix:   "arm-eabi-",
#             raspi:    "2" }
#         - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-eabi.tar.xz",
#             tarname:  "gcc-arm-9.2-2019.12-x86_64-arm-none-eabi.tar.xz",
#             dirname:  "gcc-arm-9.2-2019.12-x86_64-arm-none-eabi",
#             prefix:   "arm-none-eabi-",
#             raspi:    "2" }
#         - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2019.01/gcc-arm-8.2-2019.01-x86_64-aarch64-elf.tar.xz",
#             tarname:  "gcc-arm-8.2-2019.01-x86_64-aarch64-elf.tar.xz",
#             dirname:  "gcc-arm-8.2-2019.01-x86_64-aarch64-elf",
#             prefix:   "aarch64-elf-",
#             raspi:    "3" }
#         - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-elf.tar.xz",
#             tarname:  "gcc-arm-8.3-2019.03-x86_64-aarch64-elf.tar.xz",
#             dirname:  "gcc-arm-8.3-2019.03-x86_64-aarch64-elf",
#             prefix:   "aarch64-elf-",
#             raspi:    "3" }
        - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz",
            tarname:  "gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz",
            dirname:  "gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf",
            prefix:   "aarch64-none-elf-",
            raspi:    "3" }

    steps:
    - name: Select 32-bit QEMU
      if: matrix.config.raspi == '2'
      run: |
        echo ::set-env name=CFG_QEMU_BIN::$(echo "$HOME/local/qemu-92e53233-32/bin/qemu-system-arm")
        echo ::set-env name=CFG_QEMU_OPT::$(echo "-bios")
        echo ::set-env name=CFG_QEMU_IMG::$(echo "kernel7.img")

    - name: Select 64-bit QEMU
      if: matrix.config.raspi == '3'
      run: |
        echo ::set-env name=CFG_QEMU_BIN::$(echo "$HOME/local/qemu-4.2.0-64/bin/qemu-system-aarch64")
        echo ::set-env name=CFG_QEMU_OPT::$(echo "-kernel")
        echo ::set-env name=CFG_QEMU_IMG::$(echo "kernel8.img")

    - name: Checkout circle-stdlib
      uses: actions/checkout@v1

    - name: Cache QEMU 64-bit
      id: qemu-4_2_0-64-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/qemu-4.2.0-64
        key: ${{ runner.os }}-qemu-4_2_0-64

    - name: Install QEMU 64-bit
      if: steps.qemu-4_2_0-64-cache-id.outputs.cache-hit != 'true'
      run: |
        cd
        wget -nv https://download.qemu.org/qemu-4.2.0.tar.xz
        tar xf qemu-4.2.0.tar.xz
        cd qemu-4.2.0
        ./configure --prefix=$HOME/local/qemu-4.2.0-64 --target-list=aarch64-softmmu
        make -j
        make install

    - name: Cache QEMU 32-bit
      id: qemu-92e53233-32-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/qemu-92e53233-32
        key: ${{ runner.os }}-qemu-92e53233-32

    - name: Clone QEMU 32-bit Repository
      if: steps.qemu-92e53233-32-cache-id.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: rsta2/qemu
        ref: 92e53233035e6bef24ce79e9cebd45d670de3902
        path: qemu-32

    - name: Build QEMU 32-bit     
      if: steps.qemu-92e53233-32-cache-id.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/qemu-32
        git submodule update --init dtc
        ./configure --prefix=$HOME/local/qemu-92e53233-32 --target-list=arm-softmmu
        make -j
        make install

    - name: Cache Compiler ${{ matrix.config.dirname }}
      id: compiler-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/${{ matrix.config.dirname }}
        key: ${{ runner.os }}-compiler-${{ matrix.config.dirname }}

    - name: Install Compiler ${{ matrix.config.dirname }}
      if: steps.compiler-cache-id.outputs.cache-hit != 'true'
      run: |
        cd
        wget -nv -O ${{ matrix.config.tarname }} ${{ matrix.config.url }}
        tar -x -f ${{ matrix.config.tarname }} -C ~/local
 
    - name: Set Compiler Path ${{ matrix.config.dirname }}
      run: echo ::set-env name=PATH::$(echo "$HOME/local/${{ matrix.config.dirname }}/bin:$PATH")

    - name: Update submodules
      run: git submodule update --init --recursive
                
    - name: Configure circle-stdlib with QEMU support
      run: ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.raspi }} --qemu
        
    - name: Build libraries
      run: make -j

    - name: Build samples
      run: make build-samples
      
    - name: Run smoke test with QEMU
      run: |
        make -C samples/05-smoketest
        # Extract blank SD card image
        rm -f samples/05-smoketest/sdcard.img
        unzip -d samples/05-smoketest samples/05-smoketest/sdcard.img.zip
        # Guard against endless loop in QEMU run (120 CPU secs)
        ulimit -t 120
        $CFG_QEMU_BIN -M raspi${{ matrix.config.raspi }} $CFG_QEMU_OPT samples/05-smoketest/$CFG_QEMU_IMG -display none -nographic -semihosting -sd samples/05-smoketest/sdcard.img
