name: branch "develop"

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.config.dirname }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2019.01/gcc-arm-8.2-2019.01-x86_64-aarch64-elf.tar.xz",
            tarname:  "gcc-arm-8.2-2019.01-x86_64-aarch64-elf.tar.xz",
            dirname:  "gcc-arm-8.2-2019.01-x86_64-aarch64-elf",
            prefix:   "aarch64-elf-",
            qemu:     "$HOME/local/local/qemu-4.2.0-64/bin/qemu-system-aarch64",
            raspi:    "3",
            kernel:   "kernel8.img" }
        # - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-elf.tar.xz",
        #     tarname:  "gcc-arm-8.3-2019.03-x86_64-aarch64-elf.tar.xz",
        #     dirname:  "gcc-arm-8.3-2019.03-x86_64-aarch64-elf",
        #     prefix:   "aarch64-elf-" }
        # - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz",
        #     tarname:  "gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz",
        #     dirname:  "gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf",
        #     prefix:   "aarch64-none-elf-" }

    steps:
    - name: Checkout circle-stdlib
      uses: actions/checkout@v1

    - name: Cache QEMU 64-bit
      id: qemu-4_2_0-64-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/qemu-4.2.0-64
        key: ${{ runner.os }}-qemu-4_2_0-64

    - name: Install QEMU 64-bit
      if: steps.qemu-4_2_0-64-cache-id.outputs.cache-hit != 'true'
      run: |
        cd
        wget -nv https://download.qemu.org/qemu-4.2.0.tar.xz
        tar xf qemu-4.2.0.tar.xz
        cd qemu-4.2.0
        ./configure --prefix=$HOME/local/qemu-4.2.0-64 --target-list=aarch64-softmmu
        make -j
        make install

    - name: Cache QEMU 32-bit
      id: qemu-7d7af6c3-32-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/qemu-7d7af6c3-32
        key: ${{ runner.os }}-qemu-7d7af6c3-32

    - name: Clone QEMU 32-bit Repository
      if: steps.qemu-7d7af6c3-32-cache-id.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: rsta2/qemu
        ref: 7d7af6c31ebdb31a501adc134364826a7218db61
        path: qemu-32

    - name: Build QEMU 32-bit     
      if: steps.qemu-7d7af6c3-32-cache-id.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/qemu-32
        git submodule update --init dtc
        ./configure --prefix=$HOME/local/qemu-7d7af6c3-32 --target-list=arm-softmmu
        make -j
        make install

    - name: Cache Compiler ${{ matrix.config.dirname }}
      id: compiler-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/${{ matrix.config.dirname }}
        key: ${{ runner.os }}-compiler-${{ matrix.config.dirname }}

    - name: Install Compiler ${{ matrix.config.dirname }}
      if: steps.compiler-cache-id.outputs.cache-hit != 'true'
      run: |
        cd
        wget -nv -O ${{ matrix.config.tarname }} ${{ matrix.config.url }}
        tar -x -f ${{ matrix.config.tarname }} -C ~/local
 
    - name: Set Compiler Path ${{ matrix.config.dirname }}
      run: echo ::set-env name=PATH::$(echo "$HOME/local/${{ matrix.config.dirname }}/bin:$PATH")

    - name: Update submodules
      run: git submodule update --init --recursive
                
    - name: Configure for AArch64 Raspberry Pi with QEMU support
      run: ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.raspi }} --qemu
        
    - name: Build libraries
      run: make -j

    - name: Build samples
      run: make build-samples
      
    - name: Run smoke test with QEMU
      run: |
        make -C libs/circle/addon/qemu
        make -C samples/05-smoketest
        ${{ matrix.config.qemu }} -M raspi${{ matrix.config.raspi }} -kernel samples/05-smoketest/${{ matrix.config.kernel }} -display none -nographic -semihosting
